{
 "title": "Matplotlib - comparison",
 "time": { "from": "2019-05-07T00:00:00.000Z", "to": "2019-06-21T00:00:00.000Z" },
 "panels": [
  {
   "title": "NO2 Mean per hour",
   "type": "barchart",
   "gridPos": { "h": 18, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT date_part('hour', air_quality.datetime) AS hourly, avg(air_quality.value)\r\nfrom air_quality\r\ngroup by hourly\r\norder by hourly ASC ;"
    }
   ]
  },
  {
   "title": "NO2 by Location",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 16, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT datetime AS \"time\", location, value AS \"value\" FROM air_quality ORDER BY datetime ASC "
    }
   ]
  },
  {
   "title": "Daily mean per location",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 18, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT time_bucket('1 day', datetime) AS \"time\", location, avg(value) AS \"value\" FROM air_quality group by time,location ORDER BY time ASC LIMIT null "
    }
   ]
  }
 ]
}