version: '3.9'
services:
  timescaledb:
    image: timescale/timescaledb-ha:pg15
    container_name: timescaledb
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data:/home/postgres/pgdata/data
    network_mode: host

